name: Coding Standards

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  phpcs:
    name: PHP_CodeSniffer
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        tools: composer:v2, phpcs
    
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    
    - name: Check coding standards
      run: phpcs --standard=PSR12 src/ tests/ 